name: product-rating-service
spring.database.driverClassName: "com.mysql.jdbc.Driver"
spring.datasource.url: "jdbc:mysql://localhost:3306/stock?useSSL=false&allowPublicKeyRetrieval=true"
spring.datasource.username: "root"
spring.datasource.password: "password"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.MySQL5InnoDBDialect"
spring.jpa.hibernate.ddl-auto: "update"
